esphome:
  name: "esp32-1"
  friendly_name: "esp32-1"

# Example configuration entry
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: latest

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "********************************************"

ota:
  password: "********************************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.0.11
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-2 Fallback Hotspot"
    password: "************"

captive_portal:

# Example configuration entry 
switch:
  - platform: gpio
    name: "light 1"
    pin: 12
    #inverted: true
  - platform: gpio
    name: "light 2"
    pin: 14
  - platform: gpio
    name: "light 3"
    pin: 27
  - platform: gpio
    name: "light 4"
    pin: 26
  - platform: gpio
    name: "balcony light"
    pin: 25
  - platform: gpio
    name: "bathroom light"
    pin: 33
  - platform: gpio
    name: "bathroom fan"
    pin: 32

# Example configuration entry
i2c:
  sda: 21
  scl: 22
  scan: True

sensor:
  - platform: aht10
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 10s